baseurl = "https://example.org/"
languageCode = "en-us"
title = "Adrianne's Hugo Site"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Adrianne Padua"
    site_description = "A sample web development portfolio"
    location = "California, USA"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/adri_profpic_openhands.png"
    header_title = "ADRIANNE.dev"
    copyright = "&copy; [Adrianne Padua](https://adrianne.io)"
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "adriculous"
    facebook  = ""
    linkedin  = ""
    behance   = "adriculous"
    dribbble  = ""
    instagram = "adrimarsink"
    github    = "adriculous"
